apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-reservation-app
  namespace: flight-reservation
  labels:
    app: flight-reservation-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-reservation-app
  template:
    metadata:
      labels:
        app: flight-reservation-app
    spec:
      containers:
      - name: flight-reservation-app
        image: yugajoshi/flight-backend:1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            valueFrom:
              sectretKeyRef:
                name: mysecret
                value: db_host
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                value: db_name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                value: db_user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysecret
                value: db_pass 
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
