apiVersion: v1
kind: Secret
metadata: 
  name: mysecret
data: 
  db_host: "ZmxpZ2h0LXJkcy5jcGF3MHEyZ3k3cGsudXMtZWFzdC0yLnJkcy5hbWF6b25hd3MuY29t"
  db_name: "ZmxpZ2h0ZGI="
  db_user: "YWRtaW4="
  db_pass: "a2ZMSDU2bnpDeEtmQkNFZFNTYndNNW9neA=="


